services:
  uniclinicas_app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://uniclinicas_db:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: uniclinicas_redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - uniclinicas_db
      - uniclinicas_redis

  uniclinicas_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  uniclinicas_redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"

volumes:
  postgres_data:
  redis_data: